# Random Forest Classification

## Importing the libraries

In [1]:
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd
from sklearn.preprocessing import LabelEncoder
from sklearn.impute import SimpleImputer
import os

## Importing the dataset

In [2]:
dataset = pd.read_csv('allFeatures.csv')
dataset.replace([np.inf, -np.inf], np.nan,inplace=True)

In [3]:
dataset = pd.read_csv('allFeatures.csv')
dataset.replace([np.inf, -np.inf], np.nan,inplace=True)
dataset["EDmeanMiddleThicknessLVM"] = dataset["EDmeanMiddleThicknessLVM"].fillna( dataset["EDmeanMiddleThicknessLVM"].mean() )
dataset["EDstdMiddleThicknessLVM"] = dataset["EDstdMiddleThicknessLVM"].fillna( dataset["EDstdMiddleThicknessLVM"].mean() )
dataset["ESmeanCircularity1"] = dataset["ESmeanCircularity1"].fillna( dataset["ESmeanCircularity1"].mean() )
dataset["ESmeanCircularity3"] = dataset["ESmeanCircularity3"].fillna( dataset["ESmeanCircularity3"].mean() )
dataset["EDmeanCircularity1"] = dataset["EDmeanCircularity1"].fillna( dataset["EDmeanCircularity1"].mean() )
dataset["EDmeanCircularity2"] = dataset["EDmeanCircularity2"].fillna( dataset["EDmeanCircularity2"].mean() )
dataset["vminLVM_vminLVC"] = dataset["vminLVM_vminLVC"].fillna( dataset["vminLVM_vminLVC"].mean() )


In [4]:
dataset.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 100 entries, 0 to 99
Data columns (total 77 columns):
 #   Column                    Non-Null Count  Dtype  
---  ------                    --------------  -----  
 0   Unnamed: 0                100 non-null    int64  
 1   Height                    100 non-null    float64
 2   Weight                    100 non-null    float64
 3   BMI                       100 non-null    float64
 4   BSA                       100 non-null    float64
 5   Thickness                 100 non-null    float64
 6   EDmaxThicknessRVC         100 non-null    float64
 7   EDminThicknessRVC         100 non-null    float64
 8   EDstdThicknessRVC         100 non-null    float64
 9   EDmeanThicknessRVC        100 non-null    float64
 10  EDmaxThicknessLVC         100 non-null    float64
 11  EDminThicknessLVC         100 non-null    float64
 12  EDstdThicknessLVC         100 non-null    float64
 13  EDmeanThicknessLVC        100 non-null    float64
 14  EDmaxThickn

In [5]:
dataset.isnull().sum()

Unnamed: 0         0
Height             0
Weight             0
BMI                0
BSA                0
                  ..
vstdLVC            0
vminLVC_vminRVC    0
vminLVM_vminLVC    0
vminRVC_vminLVM    0
Group              0
Length: 77, dtype: int64

In [6]:
X = dataset.iloc[:, 0:-1].values
y = dataset.iloc[:, -1].values

le = LabelEncoder()
y = le.fit_transform(y)

## Splitting the dataset into the Training set and Test set

In [7]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.2, random_state = 6)


In [8]:
print(y_train)


[3 1 3 0 4 2 2 0 0 4 3 1 2 2 4 1 4 0 4 2 1 0 2 2 1 2 2 1 1 0 4 0 1 0 4 3 2
 0 3 2 2 0 3 2 4 4 4 1 0 3 3 4 4 0 2 3 2 0 4 0 3 1 3 0 0 4 3 1 1 2 3 3 0 1
 3 4 3 4 3 0]


In [9]:
print(X_test)


[[1.70000000e+01 1.61000000e+02 7.90000000e+01 ... 1.33322612e+00
  5.90349819e-01 1.27053535e+00]
 [3.40000000e+01 1.70000000e+02 8.00000000e+01 ... 8.38535414e-01
  2.40443808e+00 4.95980947e-01]
 [0.00000000e+00 1.84000000e+02 9.50000000e+01 ... 3.10959940e+00
  8.50267380e-01 3.78216123e-01]
 ...
 [9.30000000e+01 1.64000000e+02 4.50000000e+01 ... 8.02816901e-02
  6.79824561e-01 1.83225806e+01]
 [3.70000000e+01 1.60000000e+02 5.90000000e+01 ... 7.37680438e-01
  2.23661718e+00 6.06094127e-01]
 [8.30000000e+01 1.40000000e+02 3.50000000e+01 ... 3.12231100e-01
  1.53543307e-01 2.08589744e+01]]


In [10]:
print(y_test)


[0 1 0 2 3 4 1 2 2 4 3 3 1 1 1 1 2 4 1 4]


## Feature Scaling

In [11]:
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
X_train = sc.fit_transform(X_train)
X_test = sc.transform(X_test)

In [12]:
print(X_train)

[[ 0.81083803  0.91885222  1.12514168 ... -0.54844008 -0.46886384
   1.24427806]
 [-0.70082272 -2.2392769  -1.30087217 ... -0.48571005  3.63017991
  -0.70061577]
 [ 0.5756908  -1.80367288 -0.67881733 ... -0.53140315 -0.48918045
   1.14969613]
 ...
 [ 1.14676264  0.15654519 -0.86543378 ... -0.59190558 -0.36025794
   1.38966562]
 [ 0.77724557  0.48324821  0.75190878 ... -0.4430612  -0.16602095
  -0.0771311 ]
 [-1.33907948  1.02775323 -0.30558444 ... -0.10652857 -0.56682721
  -0.08925882]]


## Training the Random Forest Classification model on the Training set

In [13]:
from sklearn.ensemble import RandomForestClassifier
classifier = RandomForestClassifier(n_estimators = 1000, criterion = 'entropy', random_state = 0)
classifier.fit(X_train, y_train)


RandomForestClassifier(criterion='entropy', n_estimators=1000, random_state=0)

## Predicting a new result

In [14]:
X_test

array([[-1.10393225, -1.04136585,  0.25426491, ..., -0.17659882,
        -0.63843931,  0.2353077 ],
       [-0.53286041, -0.06125681,  0.3164704 , ..., -0.37911444,
         0.19402418, -0.42630634],
       [-1.67500409,  1.46335724,  1.24955264, ...,  0.5506098 ,
        -0.51916623, -0.52689948],
       ...,
       [ 1.44909479, -0.71466284, -1.86072151, ..., -0.68952703,
        -0.59738041, 14.80093731],
       [-0.43208303, -1.15026686, -0.98984475, ..., -0.42040227,
         0.11701317, -0.33224913],
       [ 1.11317018, -3.32828694, -2.48277635, ..., -0.59457199,
        -0.83888461, 16.96749098]])

## Predicting the Test set results

In [15]:
y_pred = classifier.predict(X_test)
#print(np.concatenate((y_pred.reshape(len(y_pred),1), y_test.reshape(len(y_test),1)),1))

In [16]:
y_test

array([0, 1, 0, 2, 3, 4, 1, 2, 2, 4, 3, 3, 1, 1, 1, 1, 2, 4, 1, 4])

In [17]:
y_pred

array([0, 1, 0, 2, 3, 2, 1, 2, 2, 4, 3, 3, 1, 1, 2, 1, 2, 4, 1, 4])

## Making the Confusion Matrix

In [18]:
from sklearn.metrics import confusion_matrix, accuracy_score
cm = confusion_matrix(y_test, y_pred)
print(cm)
accuracy_score(y_test, y_pred)


[[2 0 0 0 0]
 [0 6 1 0 0]
 [0 0 4 0 0]
 [0 0 0 3 0]
 [0 0 1 0 3]]


0.9